# Example settings file.
#
# @package   ApiOpenStudio
# @license   This Source Code Form is subject to the terms of the ApiOpenStudio Public License.
#            If a copy of the license was not distributed with this file,
#            You can obtain one at https://www.apiopenstudio.com/license/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

debug:
  formatters:
    default:
      format: null
      date_format: null
      allow_inline_line_breaks: false
      ignore_empty_context_and_extra: true
  handlers:
    api_log_file:
      class: StreamHandler
      formatter: default
      level: ERROR
      stream: /var/log/nginx/api.log
    db_log_file:
      class: StreamHandler
      formatter: default
      level: ERROR
      stream: /var/log/nginx/db.log
    stdout:
      class: StreamHandler
      formatter: default
      level: ERROR
      stream: php://stdout
  loggers:
    api:
      handlers:
        - stdout
        - api_log_file
    db:
      handlers:
        - stdout
        - db_log_file

db:
  definition_path: "includes/Db/dbDefinition.yaml"
  driver: mysqli
  host: apiopenstudio-db
  root_password: my_s3cr3t
  username: apiopenstudio
  password: my_s3cr3t
  database: apiopenstudio
  options:
    debug: false
  charset: utf8
  collation: utf8_unicode_ci

api:
  protocols:
    - http
  base_path: "/var/www/html/"
  url: "api.docker.localhost"
  cache:
    active: false
  #  cache:
  #    active: true
  #    type: memcached
  #    servers:
  #        host: memcached.example.com
  #        port: 11211
  #        weight: 1
  #  cache:
  #    active: true
  #    type: redis
  #    servers:
  #      host: redis.example.com
  #      port: 6379
  #      password:
  default_format: json
  wrap_json_in_response_object: true
  core_account: apiopenstudio
  core_application: core
  core_resource_lock: false
  dir_public: "public/"
  dir_resources: "includes/resources/"
  dir_uploads: "~/Downloads/"
  dir_tmp: "/tmp/"
  jwt_private_key: "/etc/nginx/certs/jwt.key"
  jwt_public_key: "/etc/nginx/certs/jwt.key.pub"
  jwt_alg_type: "Rsa"
  jwt_alg: "Sha256"
  jwt_life: "+1 hour"
  jwt_issuer: "api.docker.localhost"
  jwt_permitted_for: "api.docker.localhost"
  openapi_version: "3.0.3"
  openapi_directory: "includes/openapiSchema"

email:
  from: "Admin <admin@example.com>"
  reply_to: "Contact <contact@example.com>"
  dsn: "smtp://USERNAME:PASSWORD@DOMAIN:PORT"
