http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/localhost.crt"
      keyFile: "/etc/certs/localhost.key"